const withOpacity = (variableName) => `rgb(var(${variableName}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': withOpacity('--color-on-primary-fixed'),
        'surface-container': withOpacity('--color-surface-container'),
        'secondary-fixed-dim': withOpacity('--color-secondary-fixed-dim'),
        'on-primary-fixed-variant': withOpacity('--color-on-primary-fixed-variant'),
        'surface-bright': withOpacity('--color-surface-bright'),
        error: withOpacity('--color-error'),
        'outline-variant': withOpacity('--color-outline-variant'),
        secondary: withOpacity('--color-secondary'),
        'tertiary-fixed-dim': withOpacity('--color-tertiary-fixed-dim'),
        'surface-container-lowest': withOpacity('--color-surface-container-lowest'),
        'on-tertiary-fixed': withOpacity('--color-on-tertiary-fixed'),
        'on-secondary-fixed': withOpacity('--color-on-secondary-fixed'),
        outline: withOpacity('--color-outline'),
        'on-error-container': withOpacity('--color-on-error-container'),
        'on-error': withOpacity('--color-on-error'),
        'error-container': withOpacity('--color-error-container'),
        'on-surface-variant': withOpacity('--color-on-surface-variant'),
        'primary-container': withOpacity('--color-primary-container'),
        'on-tertiary': withOpacity('--color-on-tertiary'),
        'primary-fixed': withOpacity('--color-primary-fixed'),
        'surface-dim': withOpacity('--color-surface-dim'),
        'on-background': withOpacity('--color-on-background'),
        'on-tertiary-container': withOpacity('--color-on-tertiary-container'),
        'on-surface': withOpacity('--color-on-surface'),
        'surface-tint': withOpacity('--color-surface-tint'),
        'primary-fixed-dim': withOpacity('--color-primary-fixed-dim'),
        tertiary: withOpacity('--color-tertiary'),
        primary: withOpacity('--color-primary'),
        'surface-container-high': withOpacity('--color-surface-container-high'),
        'on-primary-container': withOpacity('--color-on-primary-container'),
        'surface-container-highest': withOpacity('--color-surface-container-highest'),
        'on-primary': withOpacity('--color-on-primary'),
        'secondary-fixed': withOpacity('--color-secondary-fixed'),
        'on-secondary-container': withOpacity('--color-on-secondary-container'),
        'on-tertiary-fixed-variant': withOpacity('--color-on-tertiary-fixed-variant'),
        'tertiary-fixed': withOpacity('--color-tertiary-fixed'),
        'surface-variant': withOpacity('--color-surface-variant'),
        surface: withOpacity('--color-surface'),
        'surface-container-low': withOpacity('--color-surface-container-low'),
        'inverse-primary': withOpacity('--color-inverse-primary'),
        background: withOpacity('--color-background'),
        'inverse-surface': withOpacity('--color-inverse-surface'),
        'secondary-container': withOpacity('--color-secondary-container'),
        'on-secondary': withOpacity('--color-on-secondary'),
        'tertiary-container': withOpacity('--color-tertiary-container'),
        'on-secondary-fixed-variant': withOpacity('--color-on-secondary-fixed-variant'),
        'inverse-on-surface': withOpacity('--color-inverse-on-surface'),
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
